apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-lab
  template:
    metadata:
      labels:
        app: devops-lab
    spec:
      containers:
        - name: devops-lab
          image: javanshir301/devops-lab:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: devops-lab-service
spec:
  selector:
    app: devops-lab
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer

